version: '3'
services:
  laravel:
    container_name: laravel
    restart: always
    build: .
    env_file:
      - ./envs/.env

  app:
    container_name: app
    restart: always
    build: .
    env_file:
      - ./envs/.env.test

  nginx:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - laravel
      - app
